version: '3.6'
services:
  eznvr:
    container_name: zoraxy
    hostname: zoraxy
    image: cyb3rdoc/zoraxy:latest
    ports:
      - 8000:8000
    volumes:
      - /path/to/zoraxy:/zoraxy
    restart: unless-stopped
